### ISSUE TITLE
Loading model error via comfyui official LoadControlNetModel node

### ISSUE THREAD

**Issue by chflame163** [TheMistoAI/MistoLine#1]
感谢您分享这么奇妙的模型。
我通过comfyui官方的LoadControlNetModel节点加载模型时出错，两个模型都尝试过，出现同样的错误。
<img width="1407" alt="微信图片_20240508210020" src="https://github.com/TheMistoAI/MistoLine/assets/130118553/8b206b6c-1584-431e-bc25-599f222367bf">

<img width="726" alt="微信图片_20240508210203" src="https://github.com/TheMistoAI/MistoLine/assets/130118553/e8822825-ae52-4825-b2a8-c7b6046c7337">

**Comment by baizh0u** [comment]
请把ComfyUI更新到最新版本，再尝试...

**Comment by chflame163** [comment]
> 请把ComfyUI更新到最新版本，再尝试...

我把ComfyUI更新到最新版本仍然如此。最后重新下载ComfyUI官方版本就没有报错了。谢谢回复。
