### ISSUE TITLE
Error occurred when executing AnyLinePreprocessor:  operands could not be broadcast together with shapes (57,2276,3,3) (57,2276,1280,3)

### ISSUE THREAD

**Issue by Seafood0808** [TheMistoAI/MistoLine#14]
The comfyuiUI rendering encounters the following situation ; comfyuiUI渲染時碰到了以下狀況

Error occurred when executing AnyLinePreprocessor:  operands could not be broadcast together with shapes (57,2276,3,3) (57,2276,1280,3)

Is there a solution?;請問有解嗎?

**Comment by xyhStruggler** [comment]
是批量出图了吗？目前Anyline暂不支持批量

**Comment by Seafood0808** [comment]
> 是批量出图了吗？目前Anyline暂不支持批量

感謝我有去找答案了，下午的時候就確定無法批量生圖了，本來是想走Animdeiff

**Comment by xyhStruggler** [comment]
> > 是批量出图了吗？目前Anyline暂不支持批量
> 
> 感謝我有去找答案了，下午的時候就確定無法批量生圖了，本來是想走Animdeiff

可以找一个batch image的插件实现

**Comment by Seafood0808** [comment]
> > > 是批量出图了吗？目前Anyline暂不支持批量
> > 
> > 
> > 感謝我有去找答案了，下午的時候就確定無法批量生圖了，本來是想走Animdeiff
> 
> 可以找一个batch image的插件实现有試過了一樣不行
