### ISSUE TITLE
No such file or directory: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\MistoLine\\__init__.py'

### ISSUE THREAD

**Issue by ping3839** [TheMistoAI/MistoLine#15]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\MistoLine\\__init__.py'

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\MistoLine module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\MistoLine\\__init__.py'

**Comment by xyhStruggler** [comment]
The example workflow uses Anyline preprocessor. You need to follow the instructions here: https://github.com/TheMistoAI/ComfyUI-Anyline to install it in your ComfyUI
