### ISSUE TITLE
rank256 and fp16 config.json

### ISSUE THREAD

**Issue by fkjkey** [TheMistoAI/MistoLine#16]
Whether
[mistoLine_rank256.safetensors](https://huggingface.co/TheMistoAI/MistoLine/blob/main/mistoLine_rank256.safetensors)
and
[diffusion_pytorch_model.fp16.safetensors](https://huggingface.co/TheMistoAI/MistoLine/blob/main/diffusion_pytorch_model.fp16.safetensors)
use the same
[config.json](https://huggingface.co/TheMistoAI/MistoLine/blob/main/config.json)
when I use diffusers

**Comment by xyhStruggler** [comment]
The fp16 version is recommended for diffusers.
