### ISSUE TITLE
大佬 安装不上 载入又报错是什么情况？还要安装什么依赖? 已经升到最新版本

### ISSUE THREAD

**Issue by bbggkk** [TheMistoAI/MistoLine#18]
![212121](https://github.com/TheMistoAI/MistoLine/assets/65471489/ce69d060-f5a3-43b1-91eb-6c60ef4470b9)

**Comment by xyhStruggler** [comment]
看不到具体的报错信息，请问安装https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#installation了吗？

**Comment by bbggkk** [comment]
> 看不到具体的报错信息，请问安装https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#installation 了吗？

原来是缺这个，可以了，感谢解答
