### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by fofr** [TheMistoAI/MistoLine#3]
Your README says:

> We have open-sourced the corresponding model weight files for non-commercial use by individual users.

But your license is more permissive and allows commercial use:

https://github.com/TheMistoAI/MistoLine/blob/main/LICENSE.md
https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/blob/main/LICENSE.md

Just double-checking then, these weights can be used commercially?

**Comment by xyhStruggler** [comment]
Sorry for the confusion.
As MistoLine is still an experimental model, we haven't conducted a comprehensive assessment of it. There is a high commercial risk associated with its use, so currently, the model can not be used commercially. 
We will change the LICENSE asap

**Comment by xyhStruggler** [comment]
Sorry for the confusion.
Yes, you can follow the license. I've updated the README.
